// Errors
export const ERROR = 'ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// Success
export const SET_SUCCESS = 'SET_SUCCESS'
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS'

// billers
export const FETCHING_BILLER_PROFILES = 'FETCHING_BILLER_PROFILES'
export const FETCH_BILLER_PROFILES = 'FETCH_BILLER_PROFILES'
export const FETCHING_BILLER_CATEGORIES = 'FETCHING_BILLER_CATEGORIES'
export const FETCH_BILLER_CATEGORIES = 'FETCH_BILLER_CATEGORIES'
export const CREATING_BILLER = 'CREATING_BILLER'
export const CREATE_BILLER = 'CREATE_BILLER'
export const BILLERS_ERROR = 'BILLERS_ERROR'

// invoices
export const FETCHING_INVOICES = 'FETCHING_INVOICES'
export const FETCH_INVOICES = 'FETCH_INVOICES'
export const CREATING_INVOICE = 'CREATING_INVOICE'
export const CREATE_INVOICE = 'CREATE_INVOICE'
export const UPDATING_INVOICE = 'UPDATING_INVOICE'
export const UPDATE_INVOICE = 'UPDATE_INVOICE'
export const INVOICES_ERROR = 'INVOICES_ERROR'

// payment pages
export const FETCHING_PAYMENT_PAGES = 'FETCHING_PAYMENT_PAGES'
export const FETCH_PAYMENT_PAGES = 'FETCH_PAYMENT_PAGES'
export const CREATING_PAYMENT_PAGE = 'CREATING_PAYMENT_PAGE'
export const CREATE_PAYMENT_PAGE = 'CREATE_PAYMENT_PAGE'
export const UPDATING_PAYMENT_PAGE = 'UPDATING_PAYMENT_PAGE'
export const UPDATE_PAYMENT_PAGE = 'UPDATE_PAYMENT_PAGE'
export const PAYMENT_PAGES_ERROR = 'PAYMENT_PAGES_ERROR'

// payment items
export const FETCHING_ITEM_CATEGORIES = 'FETCHING_ITEM_CATEGORIES'
export const FETCH_ITEM_CATEGORIES = 'FETCH_ITEM_CATEGORIES'
export const FETCHING_PAYMENT_ITEMS = 'FETCHING_PAYMENT_ITEMS'
export const FETCH_PAYMENT_ITEMS = 'FETCH_PAYMENT_ITEMS'
export const CREATING_PAYMENT_ITEM = 'CREATING_PAYMENT_ITEM'
export const CREATE_PAYMENT_ITEM = 'CREATE_PAYMENT_ITEM'
export const UPDATING_PAYMENT_ITEM = 'UPDATING_PAYMENT_ITEM'
export const UPDATE_PAYMENT_ITEM = 'UPDATE_PAYMENT_ITEM'
export const PAYMENT_ITEMS_ERROR = 'PAYMENT_ITEMS_ERROR'

// transactions
export const FETCHING_TRANSACTIONS = 'FETCHING_TRANSACTIONS'
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS'
export const CREATING_TRANSACTION = 'CREATING_TRANSACTION'
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION'
export const UPDATING_TRANSACTION = 'UPDATING_TRANSACTION'
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'
export const TRANSACTIONS_ERROR = 'TRANSACTIONS_ERROR'

// sub-accounts
export const FETCHING_SUB_ACCOUNTS = 'FETCHING_SUB_ACCOUNTS'
export const FETCH_SUB_ACCOUNTS = 'FETCH_SUB_ACCOUNTS'
export const CREATING_SUB_ACCOUNT = 'CREATING_SUB_ACCOUNT'
export const CREATE_SUB_ACCOUNT = 'CREATE_SUB_ACCOUNT'
export const UPDATING_SUB_ACCOUNT = 'UPDATING_SUB_ACCOUNT'
export const UPDATE_SUB_ACCOUNT = 'UPDATE_SUB_ACCOUNT'
export const SUB_ACCOUNTS_ERROR = 'SUB_ACCOUNTS_ERROR'

// customers
export const FETCHING_CUSTOMERS = 'FETCHING_CUSTOMERS'
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS'
export const CREATING_CUSTOMER = 'CREATING_CUSTOMER'
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER'
export const UPDATING_CUSTOMER = 'UPDATING_CUSTOMER'
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'
export const CUSTOMERS_ERROR = 'CUSTOMERS_ERROR'

// Api Keys
export const FETCHING_API_KEYS = 'FETCHING_API_KEYS'
export const FETCH_API_KEYS = 'FETCH_API_KEYS'
export const CREATING_API_KEY = 'CREATING_API_KEY'
export const CREATE_API_KEY = 'CREATE_API_KEY'
export const UPDATING_API_KEY = 'UPDATING_API_KEY'
export const UPDATE_API_KEY = 'UPDATE_API_KEY'

// teammates
export const FETCHING_INVITES = 'FETCHING_INVITES'
export const FETCH_INVITES = 'FETCH_INVITES'
export const FETCHING_TEAMMATES = 'FETCHING_TEAMMATES'
export const FETCH_TEAMMATES = 'FETCH_TEAMMATES'
export const CREATING_TEAMMATE = 'CREATING_TEAMMATE'
export const CREATE_TEAMMATE = 'CREATE_TEAMMATE'
export const UPDATING_TEAMMATE = 'UPDATING_TEAMMATE'
export const UPDATE_TEAMMATE = 'UPDATE_TEAMMATE'
export const TEAMMATES_ERROR = 'TEAMMATES_ERROR'

// banks
export const FETCHING_BANKS = 'FETCHING_BANKS'
export const FETCH_BANKS = 'FETCH_BANKS'

export const PAYMENTS_ERROR = 'PAYMENTS_ERROR'
